version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.test
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    tty: true
    command: 'yarn dev'

  api:
    build:
      context: .
      dockerfile: api/Dockerfile.test
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    tty: true
    command: 'yarn start:dev'
