import Head from 'next/head'
import Navbar from '../components/common/Navbar'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Cooking-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <h1>Welcome to Cooking-app!</h1>
      </main>
    </div>
  )
}

export default Home
