import React, { VFC } from 'react'
import Head from 'next/head'
import { useAppSelector } from '../../re-ducks/hooks'
import {
  selectAuthLoading,
  selectIsAuthenticated,
  selectUserRole,
} from '../../re-ducks/auth/authSlice'
import Recipes from '../recipe/Recipes'
import { IRecipe } from '../../re-ducks/recipe/type'
import Alert from './Alert'

type Props = {
  recipes: IRecipe[]
}

const Home: VFC<Props> = (props) => {
  const loading = useAppSelector(selectAuthLoading)
  const isAuthenticated = useAppSelector(selectIsAuthenticated)
  const userRole = useAppSelector(selectUserRole)

  console.log('role', userRole)

  const guestView = (
    <>
      <h2>ゲストページ</h2>
    </>
  )

  const userView = (
    <>
      <h2>ユーザーページ</h2>
    </>
  )

  const adminView = (
    <>
      <h2>管理者ページ</h2>
    </>
  )

  const Views = () => {
    if (isAuthenticated && userRole === 'user') {
      return userView
    } else if (isAuthenticated && userRole === 'admin') {
      return adminView
    } else {
      return guestView
    }
  }

  return (
    <div>
      <Head>
        <title>Cooking-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Cooking-app!</h1>
        <Alert />
        {!loading && (
          <>
            <Views />
            <Recipes {...props} />
          </>
        )}
      </main>
    </div>
  )
}

export default Home
