import React, { useEffect } from 'react'
import Head from 'next/head'
import { useAppSelector, useAppDispatch } from '../../re-ducks/hooks'
import {
  selectAuthLoading,
  selectIsAuthenticated,
  selectUserRole,
} from '../../re-ducks/auth/authSlice'
import { fetchAllRecipes } from '../../re-ducks/recipe/recipeSlice'

const Home = () => {
  const dispatch = useAppDispatch()
  useEffect(() => {
    dispatch(fetchAllRecipes())
  }, [])

  const loading = useAppSelector(selectAuthLoading)
  const isAuthenticated = useAppSelector(selectIsAuthenticated)
  const userRole = useAppSelector(selectUserRole)

  console.log('role', userRole)

  const guestView = (
    <>
      <h2>ゲストページ</h2>
    </>
  )

  const userView = (
    <>
      <h2>ユーザーページ</h2>
    </>
  )

  const adminView = (
    <>
      <h2>管理者ページ</h2>
    </>
  )

  const Views = () => {
    if (isAuthenticated && userRole === 'user') {
      return userView
    } else if (isAuthenticated && userRole === 'admin') {
      return adminView
    } else {
      return guestView
    }
  }

  return (
    <div>
      <Head>
        <title>Cooking-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Cooking-app!</h1>
        {!loading && (
          <>
            <Views />
          </>
        )}
      </main>
    </div>
  )
}

export default Home
